## Configurable
go_artifact: go1.16.6.linux-amd64.tar.gz
go_binary_base: https://mirrors.ustc.edu.cn/golang/

## Fixed
go_destdir: /tmp/golang_archive/
go_download_url: "{{ go_binary_base }}{{ go_artifact }}"
